#server.port=9002
#spring.jpa.show-sql=false
#spring.datasource.url=jdbc\:postgresql\://127.0.0.1\:5432/${registru.database.name}
#spring.datasource.username=postgres
#spring.datasource.password=root
#registru.database.name=product


# portul t?u (op?ional)
server.port=9002

# opre?te autoconfigurarea de DB/JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
